# status_constants.py

STATUS_NEW = "new"
STATUS_QUEUED = "queued"
STATUS_WORKER_IN_PROGRESS = "worker_in_progress"
STATUS_WORKER_COMPLETED = "worker_completed"
STATUS_WORKER_FAILED = "worker_failed"
STATUS_RETRYING = "retrying"
STATUS_FINE_TUNING = "fine_tuning"
STATUS_COMPLETED_SUCCESS = "completed_success"
STATUS_COMPLETED_PARTIAL = "completed_partial"
STATUS_FAILED = "failed"

ALL_TASK_STATUSES = {
    STATUS_NEW,
    STATUS_QUEUED,
    STATUS_WORKER_IN_PROGRESS,
    STATUS_WORKER_COMPLETED,
    STATUS_WORKER_FAILED,
    STATUS_RETRYING,
    STATUS_FINE_TUNING,
    STATUS_COMPLETED_SUCCESS,
    STATUS_COMPLETED_PARTIAL,
    STATUS_FAILED,
}

# In db/status_constants.py
JOB_STATUS_NEW = "new"
JOB_STATUS_QUEUED = "queued"
JOB_STATUS_IN_PROGRESS = "in_progress"
JOB_STATUS_COMPLETED_SUCCESS = "completed_success"
JOB_STATUS_COMPLETED_PARTIAL = "completed_partial"
JOB_STATUS_FAILED = "failed"

ALL_JOB_STATUSES = {
    JOB_STATUS_NEW,
    JOB_STATUS_QUEUED,
    JOB_STATUS_IN_PROGRESS,
    JOB_STATUS_COMPLETED_SUCCESS,
    JOB_STATUS_COMPLETED_PARTIAL,
    JOB_STATUS_FAILED,
}